services:
  postgres:
    image: postgres
    container_name: postgres_teamer
    restart: always
    ports:
      - 5437:5432
    environment:
      - POSTGRES_DB=teamer
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres